apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    environment: springboot-petclinic-development
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: springboot-petclinic-development
  template:
    metadata:
      labels:
        environment: springboot-petclinic-development
